### ISSUE TITLE
dingsen.py - problem when opening file

### ISSUE THREAD

**Issue by vegro90** [sloydsalen/Dingsen#14]
# Issue
When running _dingsen.py_ its stats listening to serial, but opening a file in _Dingsen_ results in this error message
```Writing to file: False
Traceback (most recent call last):
  File "dingsen.py", line 169, in <module>
    dings.writeAndLiveplot()
  File "dingsen.py", line 103, in writeAndLiveplot
    with open(filename, 'a') as f:
TypeError: coercing to Unicode: need string or buffer, bool found
```

**Comment by vegro90** [comment]
# Resolved!
